###发送注册验证短信
GET http://{{host}}/sms/code/15382355341?type=register

###发送修改密码验证短信
POST http://{{host}}/sms/code
Content-Type: application/json

{
  "phone": "15382355341",
  "type": "changePassword"
}

###发送绑定手机号验证短信
POST http://{{host}}/sms/code
Content-Type: application/json

{
  "phone": "15382355341",
  "type": "bindPhone"
}

###用户注册
POST http://{{host}}/register/phone
Content-Type: application/json

{
  "phone": "15382355341",
  "password": "114514",
  "nickname": "YY",
  "code": "1234",
  "signedNotice": true
}

###用户登录
POST http://{{host}}/login/phone
Content-Type: application/json

{
  "phone": "15382355341",
  "password": "114514"
}

###绑定手机号
POST http://{{host}}/bind/phone
Authorization:{{auth_token}}
Content-Type: application/json

{
  "phone": "15382355341",
  "code": "1234"
}

###用户登录
POST http://{{host}}/login/phone
Content-Type: application/json

{
  "phone": "15382355341",
  "password": "114514"
}

> {% client.global.set("auth_token",response.body.data.token);%}

###签署服务协议
GET http://{{host}}/sign/notice
Authorization:{{auth_token}}

> {% client.global.set("auth_token",response.body.data.token);%}

###用户修改密码
POST http://{{host}}/changePassword/phone/15382355341
Content-Type: application/json

{
  "newPassword": "114514",
  "code": "1234"
}

> {% client.global.set("auth_token",response.body.data.token);%}

###获取用户个人信息
GET http://{{host}}/userInfo/49
Authorization:{{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###搜索用户个人信息
GET http://{{host}}/userInfo/search?nickname=YY
Authorization:{{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###用户修改个人信息
PUT http://{{host}}/userInfo/me
Authorization:{{auth_token}}
Content-Type: application/json

{
  "avatarUrl": "https://www.baidu.com"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取用户简历信息
GET http://{{host}}/resume/me
Authorization:{{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###修改用户简历
PUT http://{{host}}/resume
Authorization: {{auth_token}}
Content-Type: application/json

{
  "name": "姚懿",
  "phone": "15382355341",
  "email": "269294523@qq.com",
  "gender": "男",
  "birth": "2000-6",
  "highestDegree": "本科",
  "identity": "学生",
  "currentGrade": "大三",
  "workPlace": "杭州",
  "profession": "web后端开发工程师",
  "eduExperiences": [
    {
      "degree": "本科",
      "school": "杭州电子科技大学",
      "specialty": "计算机科学与技术",
      "grade": "20%-50%",
      "startTime": "2018-09",
      "endTime": "2022-06"
    }
  ],
  "schoolExperiences": [
    {
      "organization": "杭州电子科技大学焦点摄影工作室",
      "post": "部长",
      "startTime": "2019-5",
      "endTime": "2020-5",
      "description": "负责咕叽咕叽咕叽咕叽咕叽"
    }
  ],
  "projectExperiences": [
    {
      "name": "\"城市鹰眼\"智慧交通大数据挖掘系统",
      "content": "项目经理，架构师，后端开发工程师，大数据开发工程师",
      "startTime": "2020-1",
      "endTime": "2020-6",
      "description": "一款咕叽咕叽咕叽咕叽咕叽"
    }
  ],
  "practiceExperiences": [],
  "honors": [
    {
      "name": "杭州电子科技大学校服务外包创新创业竞赛校一等奖",
      "time": "2020-5",
      "description": "咕叽咕叽咕叽咕叽咕叽咕叽"
    }
  ],
  "projectSkill": "摸鱼",
  "intro": "咕叽咕叽咕叽咕叽咕叽"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目列表
GET http://{{host}}/project?pageNum=1&pageSize=5&userId=49
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目详细信息
GET http://{{host}}/project/70
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目所有成员信息
GET http://{{host}}/project/70/members
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目所有资源信息
GET http://{{host}}/project/7/resources
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看收藏资源列表
GET http://{{host}}/project/collection
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###收藏资源
POST http://{{host}}/project/collection/70
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###取消收藏资源
DELETE http://{{host}}/project/collection/70
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###判断收藏资源
GET http://{{host}}/project/collection/70
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###新建项目
POST http://{{host}}/project
Authorization: {{auth_token}}
Content-Type: application/json

{
  "name": "基于大数据的叽咕叽咕叽咕诱捕系统",
  "compId": 1,
  "intro": "叽咕叽咕叽咕",
  "awardLevel": 11,
  "awardTime": "2019-06"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###删除项目
DELETE http://{{host}}/project/15
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###修改项目信息
PUT http://{{host}}/project/7
Authorization: {{auth_token}}
Content-Type: application/json

{
  "tags": "服务外包 创新创业"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###添加项目成员
POST http://{{host}}/project/member/70
Authorization: {{auth_token}}
Content-Type: application/json

{
  "memberUserId": 49,
  "rank": 1,
  "job": "队长",
  "editable": 1
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###修改项目成员信息
PUT http://{{host}}/project/member/70/49
Authorization: {{auth_token}}
Content-Type: application/json

{
  "job": "队长",
  "rank": 4
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###批量修改项目成员信息
PUT http://{{host}}/project/members/1
Authorization: {{auth_token}}
Content-Type: application/json

[
  {
    "memberPhone": "15382355341",
    "rank": 2
  },
  {
    "memberPhone": "13819154341",
    "rank": 1
  }
]

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###删除项目成员
DELETE http://{{host}}/project/member/4/15382355341
Authorization: {{auth_token}}
Content-Type: application/json

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###添加项目资源
POST http://{{host}}/project/resource/70
Authorization: {{auth_token}}
Content-Type: application/json

{
  "type": 1,
  "name": "项目咕叽书",
  "filename": "aaab.doc"
}

###修改项目资源
PUT http://{{host}}/project/resource/3
Authorization: {{auth_token}}
Content-Type: application/json

{
  "type": 2
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###删除项目资源
DELETE http://{{host}}/project/resource/74
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取贡献点排行榜总表
GET http://{{host}}/rank
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取贡献点排行榜个人排名
GET http://{{host}}/rank/me
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员发送公告
POST http://{{host}}/admin/message/systemNotice
Authorization: {{auth_token}}
Content-Type: application/json

{
  "content": "这是一篇系统公告！"
}

###管理员发送系统消息
POST http://{{host}}/admin/message/systemPrivate
Authorization: {{auth_token}}
Content-Type: application/json

{
  "receiverUserId": 50,
  "content": "第一封系统消息！"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员分页获取用户信息
GET http://{{host}}/admin/user?pageNum=1&pageSize=10
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

### 管理员获取用户信息
GET http://{{host}}/admin/user/33
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

### 修改用户公开信息
PUT http://{{host}}/admin/user/info/33
Authorization: {{auth_token}}
Content-Type: application/json

{
  "school": "杭州电子科技大学"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

### 修改用户私有信息
PUT http://{{host}}/admin/user/33
Authorization: {{auth_token}}
Content-Type: application/json

{
  "contribPoint": 500
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看未读站内信数量
GET http://{{host}}/message/count/notRead?type=private
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看站内信
GET http://{{host}}/message?pageNum=1&pageSize=10&type=private
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###根据id查看站内信
GET http://{{host}}/message/22
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###根据对话获取站内信
GET http://{{host}}/message/communication/49
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###投递站内信
POST  http://{{host}}/message
Authorization: {{auth_token}}
Content-Type: application/json

{
  "receiverUserId": 49,
  "content": "第一条站内信！"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###微信绑定
POST http://{{host}}/bind/wechat?code=053gCg1w3ikZnV2cl74w3rBPOj1gCg1C
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###微信注册登录
POST http://{{host}}/login/wechat
Content-Type: application/json

{
  "nickname": "YYa",
  "code": "073RgKFa1knK4A0qzkHa1jXO1V3RgKFB",
  "signedNotice": true
}

> {% client.global.set("auth_token",response.body.data.token);%}

###获取全部竞赛信息
GET http://{{host}}/competition
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}