###发送注册验证短信
POST https://{{host}}/sms/code
Content-Type: application/json

{
  "phone": "13819154341",
  "type": "register"
}

###发送修改密码验证短信
POST https://{{host}}/sms/code
Content-Type: application/json

{
  "phone": "15382355341",
  "type": "changePassword"
}

###发送绑定手机号验证短信
POST https://{{host}}/sms/code
Content-Type: application/json

{
  "phone": "15382355341",
  "type": "bindPhone"
}

###用户注册
POST https://{{host}}/register/phone
Content-Type: application/json

{
  "phone": "13819154341",
  "password": "114514",
  "nickname": "GZY",
  "code": "1234",
  "signedNotice": true
}

###用户登录
POST https://{{host}}/login/phone
Content-Type: application/json

{
  "phone": "15382355341",
  "password": "114514"
}

> {% client.global.set("auth_token",response.body.data.token);%}

###绑定手机号
POST https://{{host}}/bind/phone
Authorization:{{auth_token}}
Content-Type: application/json

{
  "phone": "15382355341",
  "code": "1234"
}

###签署服务协议
POST https://{{host}}/sign/notice
Authorization:{{auth_token}}

> {% client.global.set("auth_token",response.body.data.token);%}

###用户修改密码
POST https://{{host}}/changePassword/phone/15382355341
Content-Type: application/json

{
  "newPassword": "114514",
  "code": "1234"
}

> {% client.global.set("auth_token",response.body.data.token);%}

###获取用户个人信息
GET https://{{host}}/userInfo/55
Authorization:{{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###搜索用户个人信息
GET https://{{host}}/userInfo/search?nickname=YY
Authorization:{{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###用户修改个人信息
PUT https://{{host}}/userInfo/me
Authorization:{{auth_token}}
Content-Type: application/json

{
  "avatarUrl": "https://www.baidu.com"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取用户简历信息
GET https://{{host}}/resume/me
Authorization:{{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###修改用户简历
PUT https://{{host}}/resume
Authorization: {{auth_token}}
Content-Type: application/json

{
  "name": "姚懿",
  "phone": "15382355341",
  "email": "269294523@qq.com",
  "gender": "男",
  "birth": "2000-6",
  "highestDegree": "本科",
  "identity": "学生",
  "currentGrade": "大三",
  "workPlace": "杭州",
  "profession": "web后端开发工程师",
  "eduExperiences": [
    {
      "degree": "本科",
      "school": "杭州电子科技大学",
      "specialty": "计算机科学与技术",
      "grade": "20%-50%",
      "startTime": "2018-09",
      "endTime": "2022-06"
    }
  ],
  "schoolExperiences": [
    {
      "organization": "杭州电子科技大学焦点摄影工作室",
      "post": "部长",
      "startTime": "2019-5",
      "endTime": "2020-5",
      "description": "负责咕叽咕叽咕叽咕叽咕叽"
    }
  ],
  "projectExperiences": [
    {
      "name": "\"城市鹰眼\"智慧交通大数据挖掘系统",
      "content": "项目经理，架构师，后端开发工程师，大数据开发工程师",
      "startTime": "2020-1",
      "endTime": "2020-6",
      "description": "一款咕叽咕叽咕叽咕叽咕叽"
    }
  ],
  "practiceExperiences": [],
  "honors": [
    {
      "name": "杭州电子科技大学校服务外包创新创业竞赛校一等奖",
      "time": "2020-5",
      "description": "咕叽咕叽咕叽咕叽咕叽咕叽"
    }
  ],
  "projectSkill": "摸鱼",
  "intro": "咕叽咕叽咕叽咕叽咕叽"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目列表
GET https://{{host}}/project?pageNum=1&pageSize=5
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目详细信息
GET https://{{host}}/project/97
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###提交订单
POST https://{{host}}/contribPoint/order
Authorization: {{auth_token}}
Content-Type: application/json

{
  "projectId": 97,
  "resourceIds": [
    157
  ]
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###支付订单
PUT https://{{host}}/contribPoint/order/30?action=pay
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取全部已购买资源
GET https://{{host}}/project/resource/purchased
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###判断资源是否已购买
GET https://{{host}}/project/resource/purchased/check/11111
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目所有成员信息
GET https://{{host}}/project/70/members
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目所有资源信息
GET https://{{host}}/project/7/resources
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取资源信息
GET https://{{host}}/project/resource/78
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看收藏资源列表
GET https://{{host}}/project/collection
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###收藏资源
POST https://{{host}}/project/collection/78
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###取消收藏资源
DELETE https://{{host}}/project/collection/70
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###判断收藏资源
GET https://{{host}}/project/collection/70
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看资源评论
GET https://{{host}}/project/resource/score?pageNum=1&pageSize=5&projectId=72
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###评论项目
POST https://{{host}}/project/score/89
Authorization: {{auth_token}}
Content-Type: application/json

{
  "score": 4.0,
  "comment": "哈哈哈哈哈哈"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###新建项目
POST https://{{host}}/project
Authorization: {{auth_token}}
Content-Type: application/json

{
  "name": "第一个项目",
  "compId": 1,
  "intro": "第一个项目！",
  "awardLevel": 11,
  "awardTime": "2019-06"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###删除项目
DELETE https://{{host}}/project/15
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###修改项目信息
PUT https://{{host}}/project/7
Authorization: {{auth_token}}
Content-Type: application/json

{
  "tags": "服务外包 创新创业"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###添加项目成员
POST https://{{host}}/project/member/70
Authorization: {{auth_token}}
Content-Type: application/json

{
  "memberUserId": 49,
  "rank": 1,
  "job": "队长",
  "editable": 1
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###修改项目成员信息
PUT https://{{host}}/project/member/70/49
Authorization: {{auth_token}}
Content-Type: application/json

{
  "job": "队长",
  "rank": 4
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###批量修改项目成员信息
PUT https://{{host}}/project/members/1
Authorization: {{auth_token}}
Content-Type: application/json

[
  {
    "memberPhone": "15382355341",
    "rank": 2
  },
  {
    "memberPhone": "13819154341",
    "rank": 1
  }
]

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###删除项目成员
DELETE https://{{host}}/project/member/4/15382355341
Authorization: {{auth_token}}
Content-Type: application/json

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###添加项目资源
POST https://{{host}}/project/resource/94
Authorization: {{auth_token}}
Content-Type: application/json

{
  "name": "18051331 姚懿 计算机网络实验报告",
  "filename": "/94/18051331 姚懿 计算机网络实验报告.docx",
  "price": 10.0,
  "discount": 0.0,
  "type": 2
}

###修改项目资源
PUT https://{{host}}/project/resource/196
Authorization: {{auth_token}}
Content-Type: application/json

{
  "name": "hahaha",
  "typeId": 2
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###删除项目资源
DELETE https://{{host}}/project/resource/109
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取贡献点排行榜总表
GET https://{{host}}/rank
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取贡献点排行榜个人排名
GET https://{{host}}/rank/me
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员发送公告
POST https://{{host}}/admin/message/systemNotice
Authorization: {{auth_token}}
Content-Type: application/json

{
  "content": "这是一篇系统公告！"
}

###管理员发送系统消息
POST https://{{host}}/admin/message/systemPrivate
Authorization: {{auth_token}}
Content-Type: application/json

{
  "receiverUserId": 50,
  "content": "第一封系统消息！"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员分页获取用户信息
GET https://{{host}}/admin/user?pageNum=1&pageSize=10
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

### 管理员获取用户信息
GET https://{{host}}/admin/user/33
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

### 修改用户公开信息
PUT https://{{host}}/admin/user/info/33
Authorization: {{auth_token}}
Content-Type: application/json

{
  "school": "杭州电子科技大学"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

### 修改用户私有信息
PUT https://{{host}}/admin/user/33
Authorization: {{auth_token}}
Content-Type: application/json

{
  "contribPoint": 500
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看未读站内信数量
GET https://{{host}}/message/count/notRead?type=private
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看站内信
GET https://{{host}}/message?pageNum=1&pageSize=10&type=private
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###根据id查看站内信
GET https://{{host}}/message/22
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###根据对话获取站内信
GET https://{{host}}/message/communication/49
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###投递站内信
POST  https://{{host}}/message
Authorization: {{auth_token}}
Content-Type: application/json

{
  "receiverUserId": 54,
  "title": "你好呀，15382355341",
  "content": "这里是13819154341！"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###微信绑定
POST https://{{host}}/bind/wechat?code=053gCg1w3ikZnV2cl74w3rBPOj1gCg1C
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###微信注册登录
POST https://{{host}}/login/wechat
Content-Type: application/json

{
  "nickname": "YYa",
  "code": "073RgKFa1knK4A0qzkHa1jXO1V3RgKFB",
  "signedNotice": true
}

> {% client.global.set("auth_token",response.body.data.token);%}

###获取全部竞赛信息
GET https://{{host}}/competition
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取全部竞赛标签信息
GET https://{{host}}/competition/type
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###根据id获取竞赛信息
GET https://{{host}}/competition/5
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###添加竞赛标签
POST https://{{host}}/admin/competition/tag
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "学术类"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###添加竞赛信息
POST https://{{host}}/admin/competition
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "全国大学生服务外包创新创业大赛",
  "typeId": 8,
  "intro": "”中国大学生服务外包创新创业大赛“（以下简称大赛），是响应国家关于鼓励服务外包产业发展、加强服务外包人才培养的相关战略举措与号召，举办的每年一届的全国性竞赛。大赛均由中华人民共和国教育部、中华人民共和国商务部和无锡市人民政府联合主办，由国家服务外包人力资源研究院、无锡市商务局、无锡市教育局、江南大学承办。大赛的主要目的是搭建产学结合的大学生服务外包创新创业能力展示平台；促进校企交流，促进高等教育为服务经济发展提供人才保障；宣传服务经济，提升社会公众对服务外包产业发展的关注度和重视度。参赛队伍均来自中国国内高等院校，以本科生为主，自由组队。大赛开放方式竞赛，经过报名参赛、自主选题、分散备赛和集中答辩的环节，评选出相应的优秀团队。大赛在选题上呼应服务外包产业，关注服务科学；在形式上，注重学生的团队协作，在虚拟的商业环境中解决问题。赛题一方面来源于现代服务产业企业的现实需求，鼓励学生综合考虑业务模型、技术方案、商业运营等各种因素，提供完整方案，立足实际情况创新应用；另一方面，大赛还鼓励参赛团队提出有创造力的创意项目，在优秀方案的基础上实现创业，增强大学生的创新创业意识。在评审环节过程与结果并重，增强能力培养导向，尤其关注团队的综合素质、学习能力与问题解决能力。往届大赛吸引了超过五百所高校和数十家产业代表企业积极参与，收到了良好的产业影响和社会效果，在全国高校与企业中的影响力也不断提升。我们将为大赛推动产业发展，加快人才培养和宣传及服务经济的目标不断努力奋斗。努力将大赛逐步发展成广受欢迎的国际性一流竞赛。"
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看用户项目
GET https://{{host}}/project/me?pageNum=1&pageSize=5
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看系统公告
GET https://{{host}}/notice
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###发布系统公告
POST https://{{host}}/admin/notice
Authorization: {{auth_token}}
Content-Type: application/json

{
  "title": "第三个测试公告",
  "content": "第三个测试公告",
  "puttingStartTime": "2020-12-20T01:00:00.000Z",
  "puttingEndTime": "2020-12-22T01:00:00.000Z",
  "enable": true
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取资源购买记录
GET https://{{host}}/admin/project/resource/purchased/78?pageNum=1&pageSize=5
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员获取反馈
GET https://{{host}}/admin/feedback?pageNum=1&pageSize=5&userId=53
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员回复反馈
PUT https://{{host}}/admin/feedback/6
Authorization: {{auth_token}}
Content-Type: application/json

{
  "reply": "好耶",
  "status": 3,
  "level": 1
}

###创建反馈
POST https://{{host}}/feedback
Authorization: {{auth_token}}
Content-Type: application/json

{
  "content": "测试15382355341",
  "type": 1
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取用户反馈
GET https://{{host}}/feedback/me?pageNum=1&pageSize=5
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目已购资源列表
GET https://{{host}}/project/purchased/79
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###签名上传
GET https://{{host}}/userInfo/avatar/sign/upload/v2?filename=avatar.jpg
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###签名上传资源
GET https://{{host}}/project/94/resources/sign/upload/private?filename=18051331 姚懿 计算机网络实验报告.docx
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###签名下载资源
GET https://{{host}}/project/resource/107/sign/download/v2
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###签名阅读资源
GET https://{{host}}/project/resource/205/sign/read
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取项目资源信息
GET https://{{host}}/project/resource/127
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取公开资源通用签名
GET http://{{host}}/cos/sign/upload/public/v2?filename=DSC04362.jpg
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员修改项目信息
PUT https://{{host}}/admin/project/94
Authorization: {{auth_token}}
Content-Type: application/json

{
  "compName": "",
  "compId": 15
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###查看用户订单
GET https://{{host}}/contribPoint/order/me?pageNum=1&pageSize=5
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###审核项目
POST https://{{host}}/admin/project/check/94
Authorization: {{auth_token}}
Content-Type: application/json

{
  "passed": true
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###审核项目资源
POST https://{{host}}/admin/project/resource/check/187
Authorization: {{auth_token}}
Content-Type: application/json

{
  "passed": true
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###用户查看自身项目资源（edit mode）
GET https://{{host}}/project/94/resources?edit=true
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员查看项目资源
GET https://{{host}}/admin/project/94/resources
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员查看全部资源
GET https://{{host}}/admin/project/resource?pageNum=1&pageSize=5
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员获取资源购买记录
GET https://{{host}}/admin/project/resource/purchased?pageNum=1&pageSize=5
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员分页获取实名认证信息
GET https://{{host}}/admin/authentication?pageNum=1&pageSize=5
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员审核实名认证信息
PUT https://{{host}}/admin/authentication/check/59?status=1
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员创建活动
POST https://{{host}}/admin/activity
Authorization: {{auth_token}}
Content-Type: application/json

{
  "title": "测试活动",
  "intro": "进行一个活动创建的测试",
  "startTime": "2021-02-04T00:00:00.000Z",
  "endTime": "2021-05-05T00:00:00.000Z",
  "exchangeAhaPoint": 5000,
  "exchangeAhaCredit": 3000,
  "codeSum": 2000
}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员发放兑换码
GET https://{{host}}/admin/activity/code?activityId=1&count=1
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###管理员查看已发放兑换码数量
GET https://{{host}}/admin/activity/code/count?activityId=2
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}


###用户使用兑换码
POST https://{{host}}/activity/code?code=nizg8gk3
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###请求实名认证签名接口
GET https://{{host}}/authentication/sign/upload?filename=a.jpg
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取用户个人统计信息
GET https://{{host}}/statistics/me
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取轮播图资源
GET https://{{host}}/slideShow
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取用户贡献点流水
GET https://{{host}}/contribPoint/log/me?pageNum=1&pageSize=5&sortBy=ahaCredit
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}

###获取post cos签名
GET https://{{host}}/cos/sign/upload/test?filename=操作系统实验报告.docx
Authorization: {{auth_token}}

> {%if (response.headers.valueOf("Authorization")!=null){client.global.set("auth_token",response.headers.valueOf("Authorization"));}%}
