spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aha_data?serverTimezone=Hongkong
    username: root
    password: ROOT_root123
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      port: 27017
      host: 127.0.0.1
      database: aha
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapperxml/*.xml
server:
  port: 8089
jwt-config:
  secret: Gzysb233
  expireTime: 600
  refreshTokenExpireTime: 604800
file-upload-path:
  avatarPath: C:/server/avatar/
aliyun-oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI4FxzTX4h82duMDLYJagD
  accessKeySecret: oLoBad86TicKfOc5TeYe1dKjcbzbLa
  publicBucketName: aha-public
  privateBucketName: aha-resource
  expireTime: 6000
  maxSize: 500